---
initial_setup_packages:
  prerequire:
    - man
    - man-pages
    - dnf5
    - dnf5-plugins
    - python3-libdnf5
    - dnf-plugins-core # temporary for copr modules

  main:
    - "*"
    - shadow-utils
    - util-linux
    - passwd
    - cracklib-dicts
    - git
    - vim
    - jq
    - micro
    - procps-ng
    - iputils
    - wget
    - which
    - rsync
    - neofetch
    - bash-completion
    - podman
    - langpacks-ja
    - temurin-21-jdk
    - pipx
    - wslu
    - jbang
    - zip
    - groff
    # for pyenv install(build) CPytnon
    - make
    - automake
    - gcc
    - gcc-c++
    - tk-devel
    - openssl-devel
    - readline-devel
    - sqlite-devel
    - xz-devel
    - libffi-devel
